### ISSUE TITLE
Issue running faky.py (with python 3.9.7)   /   app.js 

### ISSUE THREAD

**Issue by Markus-1974** [fiblan/webcam-virtual-background#9]
when I run ./install.sh, I get 
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32
ERROR: No matching distribution found for opencv-python==4.2.0.32

And later on, when I run fake.py with python 3.9, I get the following:
`
(venv) :/home/markus/webcam-virtual-background-master/fakecam# python fake.py 
Traceback (most recent call last):
  File "/home/markus/webcam-virtual-background-master/fakecam/fake.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
`
Why?

**Comment by Markus-1974** [comment]
Seems to work better with requirements.txt
`
numpy==1.19.3
opencv-python==4.5.5.62
requests==2.23.0
pyfakewebcam==0.1.0
`

**Comment by Markus-1974** [comment]
But there is still an error with app.js

`:/home/markus/webcam-virtual-background-master/bodypix# node app.js
2022-03-06 22:23:58.150973: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2022-03-06 22:23:58.180683: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2419200000 Hz
2022-03-06 22:23:58.181197: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5576a2193560 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-03-06 22:23:58.181231: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Platform node has already been set. Overwriting the platform with [object Object].
(node:26214) UnhandledPromiseRejectionWarning: TypeError: forwardFunc is not a function
    at /home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:542:55
    at /home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:388:22
    at Engine.scopedRun (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.tidy (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:387:21)
    at kernelFunc (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:542:29)
    at /home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:553:27
    at Engine.scopedRun (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.runKernelFunc (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:551:14)
    at Engine.runKernel (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:449:21)
    at pad_ (/home/markus/webcam-virtual-background-master/bodypix/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:16854:19)
(node:26214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
